title: "GAP" # System for Computational Discrete Algebra"
subtitle: "System for Computational Discrete Algebra"
theme: just-the-docs
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dev.gap-system.org" # the base hostname & protocol for your site, e.g. http://example.com

docsurl: "https://docs.gap-system.org"

color_scheme: gap

exclude:
  - "*.g"
  - "/README.md"
  - "/etc"
  - "/tmp"
  - "/ForumArchive"
  - "/ForumArchive2"
  - "/HostedGapPackages"
  - "/Manuals"

include:
  - ".htaccess"

keep_files:
  - "ForumArchive"
  - "ForumArchive2"

liquid:
  error_mode: warn
  #strict_variables: true # commented out because it isn't supported by just-the-docs
  strict_filters: true

collections:
  Releases:
    output: true

defaults:
  - scope:
      path: ""
      type: Releases
    values:
      layout: releases

  - scope:
      path: ""
    values:
      has_toc: false
      toc: nil
      subtoc: nil
      subsubtoc: nil

favicon_ico: "favicon.ico"

scripts:
 - loadPackageTable.js