title: "GAP" # System for Computational Discrete Algebra"
subtitle: "System for Computational Discrete Algebra"
theme: just-the-docs
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dev.gap-system.org" # the base hostname & protocol for your site, e.g. http://example.com

docsurl: "https://docs.gap-system.org"

exclude:
  - "*.g"
  - "/README.md"
  - "/etc"
  - "/tmp"
  - "/ForumArchive"
  - "/ForumArchive2"
  - "/HostedGapPackages"
  - "/Manuals"

include:
  - ".htaccess"

keep_files:
  - "ForumArchive"
  - "ForumArchive2"

liquid:
  error_mode: warn
  #strict_variables: true
  strict_filters: true

collections:
  Releases:
    output: true
  Packages:
    output: true

defaults:
  - scope:
      path: ""
      type: Releases
    values:
      layout: releases

  - scope:
      path: ""
      type: Packages
    values:
      layout: packages

  - scope:
      path: "Gap3"
    values:
      nav_exclude: true

  - scope:
      path: ""
    values:
      toc: nil
      subtoc: nil
      subsubtoc: nil

scripts:
 - loadPackageTable.js